/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tjavacomun;

import bbdd.Conexion;
import com.sun.jdi.connect.spi.Connection;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import bbdd.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import bbdd.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.lang.System.Logger;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;

/**
 *
 * @author Ricardo Ibanez
 */
public class Alimento extends javax.swing.JFrame {

    String usuario = null;
    
  

    public Alimento() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("MACROSLEAF");
        setIconImage(getIconImage());
        cargarDatos();

    }

    public Alimento(String usuario) {

        this.usuario = usuario;
        System.out.println("Estamos en perfil y el nombre de usuario es " + usuario);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("MACROSLEAF");
        setIconImage(getIconImage());
        cargarDatos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        texto = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        bienvenido = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAñadir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        spinGrasas = new javax.swing.JSpinner();
        spinKcal = new javax.swing.JSpinner();
        spinProteinas = new javax.swing.JSpinner();
        spinHidratos = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texto.setFont(new java.awt.Font("Times New Roman", 1, 56)); // NOI18N
        texto.setForeground(new java.awt.Color(255, 255, 255));
        texto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/texto.png"))); // NOI18N
        getContentPane().add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 620, 150));

        btnSalir.setBackground(new java.awt.Color(0, 0, 255));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Atrás");
        btnSalir.setBorder(new javax.swing.border.MatteBorder(null));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 750, 160, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bienvenido.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bienvenido.setForeground(new java.awt.Color(0, 153, 0));
        jPanel1.add(bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 280, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/perfil_resized 70.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("Grasas por 100 gr :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 210, 30));

        btnAñadir.setBackground(new java.awt.Color(51, 153, 255));
        btnAñadir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAñadir.setForeground(new java.awt.Color(255, 255, 255));
        btnAñadir.setText("Añadir Alimento");
        btnAñadir.setBorder(new javax.swing.border.MatteBorder(null));
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });
        jPanel1.add(btnAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 160, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 204));
        jLabel6.setText("Crea tus alimentos para añadirlos a tu día");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 530, 40));

        jLabel7.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 0));
        jLabel7.setText("Nombre Alimento :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 210, 30));

        jLabel8.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 0));
        jLabel8.setText("Kcal por 100 gr :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 210, 30));

        jLabel9.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 0));
        jLabel9.setText("Proteinas por 100 gr :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 210, 30));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 310, 50));

        spinGrasas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        spinGrasas.setModel(new javax.swing.SpinnerNumberModel(0, null, 800, 1));
        spinGrasas.setOpaque(true);
        jPanel1.add(spinGrasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 110, 30));

        spinKcal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        spinKcal.setModel(new javax.swing.SpinnerNumberModel(0, null, 800, 1));
        spinKcal.setOpaque(true);
        jPanel1.add(spinKcal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 110, 30));

        spinProteinas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        spinProteinas.setModel(new javax.swing.SpinnerNumberModel(0, null, 800, 1));
        spinProteinas.setOpaque(true);
        jPanel1.add(spinProteinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 110, 30));

        spinHidratos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        spinHidratos.setModel(new javax.swing.SpinnerNumberModel(0, null, 800, 1));
        spinHidratos.setOpaque(true);
        jPanel1.add(spinHidratos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 110, 30));

        jLabel3.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3.setText("Hidratos por 100 gr :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 210, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/alimento_resized.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 150, 150));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 820, 550));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        MenuPrincipal mp = new MenuPrincipal(usuario);
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que los datos introducidos son correctos?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            try {
                Conexion.conectar();
                PreparedStatement verificar = Conexion.conectar().prepareStatement("SELECT id FROM usuarios WHERE nombre = ?");
                verificar.setString(1, usuario);

                ResultSet rs = verificar.executeQuery();
                if (rs.next()) {

                    PreparedStatement verificar2 = Conexion.conectar().prepareStatement("SELECT nombre FROM alimento WHERE nombre = ? and id_usuario = ?");
                    verificar2.setString(1, txtNombre.getText());
                    verificar2.setInt(2, obtenerIdUsuario());
                    ResultSet rs2 = verificar2.executeQuery();
                    if (rs2.next()) {
                        JOptionPane.showMessageDialog(null, "Ese Alimento ya existe en nuestra base de datos", "Alimento existente", JOptionPane.WARNING_MESSAGE);

                    } else {

                        int idUsu = rs.getInt("id");
                        PreparedStatement insertar = Conexion.conectar().prepareStatement("INSERT INTO alimento (nombre,calorias,grasas,hidratos,proteinas,id_usuario) VALUES (?,?,?,?,?,?)");
                        insertar.setString(1, txtNombre.getText());
                        insertar.setInt(2, (int) spinKcal.getValue());
                        insertar.setInt(3, (int) spinGrasas.getValue());
                        insertar.setInt(4, (int) spinHidratos.getValue());
                        insertar.setInt(5, (int) spinProteinas.getValue());
                        insertar.setInt(5, (int) spinProteinas.getValue());
                        insertar.setInt(6, idUsu);

                        insertar.executeUpdate();
                        Conexion.conectar().close();
                        JOptionPane.showMessageDialog(null, "Alimento Registrado con Éxito");
                        this.dispose();
                        MenuPrincipal mp = new MenuPrincipal(usuario);
                        mp.setVisible(true);
                        this.dispose();
                    }

                }

            } catch (SQLException e) {
                System.out.println("Error en la conexión: " + e);
            }
        } else if (respuesta == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "Introduce los nuevos datos y asegúrate de que sean correctos...", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAñadirActionPerformed
public int obtenerIdUsuario() {

        Conexion.conectar();
        PreparedStatement verificar4;
        try {
            verificar4 = Conexion.conectar().prepareStatement("SELECT id FROM usuarios WHERE nombre = ?");

            verificar4.setString(1, usuario);
            ResultSet rs = verificar4.executeQuery();
            if (rs.next()) {
                int id = rs.getInt("id");
                return id;
            } else {

                return 0;
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Recetas.class.getName()).log(Level.SEVERE, null, ex);
        }
        return 0;

    }

   

    /**
     * @param args the command line arguments
     */
    @Override
    public Image getIconImage() {
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logo.png"));

        return icono;
    }

    public static void main(String args[]) {

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alimento().setVisible(true);
            }
        });
    }

    public void cargarDatos() {

        //PARTE DE LOS DATOS
        bienvenido.setText("Bienvenido " + usuario);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bienvenido;
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner spinGrasas;
    private javax.swing.JSpinner spinHidratos;
    private javax.swing.JSpinner spinKcal;
    private javax.swing.JSpinner spinProteinas;
    private javax.swing.JLabel texto;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
