/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tjavacomun;

import bbdd.Conexion;
import com.sun.jdi.connect.spi.Connection;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import bbdd.Conexion;
import static bbdd.Conexion.conectar;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
//

/**
 *
 * @author Usuario
 */
public class ModificarDatos extends javax.swing.JFrame {

    String usuario = null;

    public ModificarDatos() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("MACROSLEAF");
        setIconImage(getIconImage());

    }

    public String getUsuario() {
        return usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public ModificarDatos(String usuario) {
        this.usuario = usuario;
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("MACROSLEAF");
        setIconImage(getIconImage());
        cargarDatos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroupSexo = new javax.swing.ButtonGroup();
        texto = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        modificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rBtnMant = new javax.swing.JRadioButton();
        rBtnPerder = new javax.swing.JRadioButton();
        rBtnGanar = new javax.swing.JRadioButton();
        txtUsu = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        spinPeso = new javax.swing.JSpinner();
        spinAltura = new javax.swing.JSpinner();
        txtPass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        mujer = new javax.swing.JRadioButton();
        hombre = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        spinEdad = new javax.swing.JSpinner();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texto.setFont(new java.awt.Font("Times New Roman", 1, 56)); // NOI18N
        texto.setForeground(new java.awt.Color(255, 255, 255));
        texto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/texto.png"))); // NOI18N
        getContentPane().add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 620, 150));

        btnSalir.setBackground(new java.awt.Color(0, 0, 255));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Atrás");
        btnSalir.setBorder(new javax.swing.border.MatteBorder(null));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 740, 160, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modificar.setBackground(new java.awt.Color(0, 0, 255));
        modificar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        modificar.setForeground(new java.awt.Color(255, 255, 255));
        modificar.setText("Modificar");
        modificar.setBorder(new javax.swing.border.MatteBorder(null));
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        jPanel1.add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 160, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("E-mail :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 170, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre Usuario :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 170, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Contraseña :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 170, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Altura (cm) :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 130, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Peso (Kg) : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 170, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Sexo :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 130, 30));

        rBtnMant.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rBtnMant);
        rBtnMant.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rBtnMant.setForeground(new java.awt.Color(0, 0, 0));
        rBtnMant.setText("Mantenerse");
        rBtnMant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnMantActionPerformed(evt);
            }
        });
        jPanel1.add(rBtnMant, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, -1, -1));

        rBtnPerder.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rBtnPerder);
        rBtnPerder.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rBtnPerder.setForeground(new java.awt.Color(0, 0, 0));
        rBtnPerder.setText("Perder Peso");
        rBtnPerder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnPerderActionPerformed(evt);
            }
        });
        jPanel1.add(rBtnPerder, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, -1, -1));

        rBtnGanar.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rBtnGanar);
        rBtnGanar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rBtnGanar.setForeground(new java.awt.Color(0, 0, 0));
        rBtnGanar.setText("Ganar Peso");
        rBtnGanar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnGanarActionPerformed(evt);
            }
        });
        jPanel1.add(rBtnGanar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, -1, -1));

        txtUsu.setBackground(new java.awt.Color(255, 255, 255));
        txtUsu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtUsu.setForeground(new java.awt.Color(0, 0, 0));
        txtUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 320, 50));

        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 280, 50));

        spinPeso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        spinPeso.setModel(new javax.swing.SpinnerNumberModel(0, null, 1000, 1));
        jPanel1.add(spinPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 90, 40));

        spinAltura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        spinAltura.setModel(new javax.swing.SpinnerNumberModel(0, null, 1000, 1));
        jPanel1.add(spinAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 90, 40));

        txtPass.setBackground(new java.awt.Color(255, 255, 255));
        txtPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPass.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 290, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Objetivo :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 130, 30));

        mujer.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupSexo.add(mujer);
        mujer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mujer.setForeground(new java.awt.Color(0, 0, 0));
        mujer.setText("Mujer");
        jPanel1.add(mujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, -1, -1));

        hombre.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupSexo.add(hombre);
        hombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hombre.setForeground(new java.awt.Color(0, 0, 0));
        hombre.setText("Hombre");
        jPanel1.add(hombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Edad");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 130, 30));

        spinEdad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        spinEdad.setModel(new javax.swing.SpinnerNumberModel(0, null, 1000, 1));
        jPanel1.add(spinEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 90, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 820, 550));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed

        int valuePeso = (int) spinPeso.getValue();
        int valueAltura = (int) spinAltura.getValue();

        ButtonModel selectedButtonModel = buttonGroup1.getSelection();
        ButtonModel selectedButtonModel1 = buttonGroupSexo.getSelection();
        int selectedObjective = -1; // Por defecto, ningún objetivo seleccionado
        int selectedSex = -1;

        if (selectedButtonModel != null) {
            if (selectedButtonModel.equals(rBtnPerder.getModel())) {
                selectedObjective = 0; // Por ejemplo, el objetivo 0
            } else if (selectedButtonModel.equals(rBtnGanar.getModel())) {
                selectedObjective = 1; // Por ejemplo, el objetivo 1
            } else if (selectedButtonModel.equals(rBtnMant.getModel())) {
                selectedObjective = 2; // Por ejemplo, el objetivo 2
            }
        }
        if (selectedButtonModel1 != null) {
            if (selectedButtonModel1.equals(hombre.getModel())) {
                selectedSex = 0; // Por ejemplo, el objetivo 0
            } else if (selectedButtonModel1.equals(mujer.getModel())) {
                selectedSex = 1; // Por ejemplo, el objetivo 1
            }
        }

        if (txtUsu.getText().length() < 5) {
            JOptionPane.showMessageDialog(null, "El nombre no puede contener menos de 5 caracteres...", "Alerta", JOptionPane.INFORMATION_MESSAGE);
        } else if (txtEmail.getText().length() < 12) {
            JOptionPane.showMessageDialog(null, "El email debe contener al menos 12 caracteres...", "Alerta", JOptionPane.INFORMATION_MESSAGE);

        } else if (txtPass.getText().length() < 6) {
            JOptionPane.showMessageDialog(null, "La Contraseña debe contener 6 caracteres ...", "Alerta", JOptionPane.INFORMATION_MESSAGE);

        } else if (valuePeso == 0 || valueAltura == 0) {
            JOptionPane.showMessageDialog(null, "Debe Rellenar el Peso y la Altura correctamente", "Alerta", JOptionPane.INFORMATION_MESSAGE);

        } else if (buttonGroup1.getSelection() == null) {

            JOptionPane.showMessageDialog(null, "Debe Marcar un OBJETIVO", "Alerta", JOptionPane.INFORMATION_MESSAGE);
        } else if (buttonGroupSexo.getSelection() == null) {

            JOptionPane.showMessageDialog(null, "Debe Marcar un Sexo", "Alerta", JOptionPane.INFORMATION_MESSAGE);
        } else {
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que los datos introducidos son correctos?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_OPTION) {
                try {
                    Conexion.conectar();
                    PreparedStatement verificar = Conexion.conectar().prepareStatement("SELECT * FROM Usuarios WHERE nombre = ?");
                    verificar.setString(1, getUsuario());
                    ResultSet rs = verificar.executeQuery();
                    if (rs.next()) {
                        String updateSQL = "UPDATE Usuarios SET nombre = ?, email = ?, contraseña = ?, altura = ?, peso = ?, objetivo = ?, sexo = ?, pesoActual = ?, edad = ? WHERE nombre = ?";

                        PreparedStatement insertar = Conexion.conectar().prepareStatement(updateSQL);
                        insertar.setString(1, txtUsu.getText());
                        insertar.setString(2, txtEmail.getText());
                        insertar.setString(3, txtPass.getText());
                        insertar.setInt(4, (int) spinAltura.getValue());
                        insertar.setInt(5, (int) spinPeso.getValue());
                        insertar.setInt(6, selectedObjective);
                        insertar.setInt(7, selectedSex);
                        insertar.setString(8, spinPeso.getValue().toString());
                        insertar.setInt(9, (int) spinEdad.getValue());
                        insertar.setString(10, getUsuario());

                        System.out.println(selectedObjective);
                        insertar.executeUpdate();
                        Conexion.conectar().close();
                        JOptionPane.showMessageDialog(null, "Usuario Actualizado con Éxito");
                        this.dispose();
                        Main mp = new Main();
                        mp.setVisible(true);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Ha habido un Error, contacte con el Desarrollador...", "Información", JOptionPane.INFORMATION_MESSAGE);

                    }
                } catch (SQLException e) {
                    System.out.println("Error en la conexión: " + e);
                }
            } else if (respuesta == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "Introduce los nuevos datos y asegúrate de que sean correctos...", "Información", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_modificarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        MenuPrincipal mp = new MenuPrincipal(usuario);
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void rBtnMantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnMantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBtnMantActionPerformed

    private void rBtnPerderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnPerderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBtnPerderActionPerformed

    private void rBtnGanarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnGanarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBtnGanarActionPerformed

    private void txtUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuActionPerformed

    }//GEN-LAST:event_txtUsuActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    @Override
    public Image getIconImage() {
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logo.png"));

        return icono;
    }

    public static void main(String args[]) {

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarDatos().setVisible(true);
            }
        });
    }

    public void cargarDatos() {

        txtUsu.setText(usuario);

        try {
            Conexion.conectar();
            PreparedStatement ps = Conexion.conectar().prepareStatement("SELECT * FROM Usuarios WHERE nombre = ?");
            ps.setString(1, usuario);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {

                spinPeso.setValue(rs.getInt(9));
                spinAltura.setValue(rs.getInt(5));
                spinEdad.setValue(rs.getInt(10));
                txtEmail.setText(rs.getString(3));
                txtPass.setText(rs.getString(4));
                int sexo = rs.getInt(8);

                if (sexo != -1) {

                    if (sexo == 0) {

                        hombre.setSelected(true);
                    } else {

                        mujer.setSelected(true);

                    }

                }

                String objetivoBd = rs.getString(7);
                if (objetivoBd != null) {

                    if (objetivoBd.equals("0")) {
                        rBtnPerder.setSelected(true);

                    } else if (objetivoBd.equals("1")) {
                        rBtnGanar.setSelected(true);

                    } else {

                        rBtnMant.setSelected(true);

                    }

                }

            }

            Conexion.conectar().close();

        } catch (SQLException e) {

            System.err.println("Error en la base de datos " + e);

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroupSexo;
    private javax.swing.JLabel fondo;
    private javax.swing.JRadioButton hombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modificar;
    private javax.swing.JRadioButton mujer;
    private javax.swing.JRadioButton rBtnGanar;
    private javax.swing.JRadioButton rBtnMant;
    private javax.swing.JRadioButton rBtnPerder;
    private javax.swing.JSpinner spinAltura;
    private javax.swing.JSpinner spinEdad;
    private javax.swing.JSpinner spinPeso;
    private javax.swing.JLabel texto;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsu;
    // End of variables declaration//GEN-END:variables
}
