/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tjavacomun;

import bbdd.Conexion;
import com.sun.jdi.connect.spi.Connection;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import bbdd.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import bbdd.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Ricardo Ibanez
 */
public class Perfil extends javax.swing.JFrame {

    String usuario = null;

    public Perfil() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("MACROSLEAF");
        setIconImage(getIconImage());
        cargarDatos();

    }

    public Perfil(String usuario) {

        this.usuario = usuario;
        System.out.println("Estamos en perfil y el nombre de usuario es " + usuario);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("MACROSLEAF");
        setIconImage(getIconImage());
        cargarDatos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        texto = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        bienvenido = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        altura = new javax.swing.JLabel();
        objetivo = new javax.swing.JLabel();
        pesoInicial = new javax.swing.JLabel();
        pesoActual = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        objetivo1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        grasas = new javax.swing.JLabel();
        proteinas = new javax.swing.JLabel();
        hidratos = new javax.swing.JLabel();
        calorias = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        nota = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texto.setFont(new java.awt.Font("Times New Roman", 1, 56)); // NOI18N
        texto.setForeground(new java.awt.Color(255, 255, 255));
        texto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/texto.png"))); // NOI18N
        getContentPane().add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 620, 150));

        btnSalir.setBackground(new java.awt.Color(0, 0, 255));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Atrás");
        btnSalir.setBorder(new javax.swing.border.MatteBorder(null));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 750, 160, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bienvenido.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bienvenido.setForeground(new java.awt.Color(0, 153, 0));
        bienvenido.setText("Bienvenido Link1234");
        jPanel1.add(bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 280, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/perfil_resized 70.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 153, 51), new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setAlignmentX(1.0F);
        jSeparator4.setAlignmentY(1.0F);
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 30, 80));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator5.setAlignmentX(1.0F);
        jSeparator5.setAlignmentY(1.0F);
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 30, 80));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator6.setAlignmentX(1.0F);
        jSeparator6.setAlignmentY(1.0F);
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 30, 80));

        altura.setBackground(new java.awt.Color(0, 0, 0));
        altura.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        altura.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 60, 20));

        objetivo.setBackground(new java.awt.Color(0, 0, 0));
        objetivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        objetivo.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(objetivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 70, 20));

        pesoInicial.setBackground(new java.awt.Color(0, 0, 0));
        pesoInicial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pesoInicial.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(pesoInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 60, 20));

        pesoActual.setBackground(new java.awt.Color(0, 0, 0));
        pesoActual.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pesoActual.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(pesoActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 60, 20));

        nombre.setBackground(new java.awt.Color(0, 0, 0));
        nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nombre.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 80, 20));

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator7.setAlignmentX(1.0F);
        jSeparator7.setAlignmentY(1.0F);
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 30, 80));

        jPanel5.setBackground(new java.awt.Color(0, 153, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Lucida Console", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("  Nombre      Peso Inicial   Peso Actual    Objetivo    Altura");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 4, 530, 20));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 30));

        objetivo1.setBackground(new java.awt.Color(0, 0, 0));
        objetivo1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        objetivo1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(objetivo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 70, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 540, 80));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 153, 51), new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(1.0F);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 30, 80));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setAlignmentX(1.0F);
        jSeparator2.setAlignmentY(1.0F);
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 30, 80));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(1.0F);
        jSeparator3.setAlignmentY(1.0F);
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 30, 80));

        grasas.setBackground(new java.awt.Color(0, 0, 0));
        grasas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        grasas.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(grasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 50, 20));

        proteinas.setBackground(new java.awt.Color(0, 0, 0));
        proteinas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        proteinas.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(proteinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 60, 20));

        hidratos.setBackground(new java.awt.Color(0, 0, 0));
        hidratos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hidratos.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(hidratos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 60, 20));

        calorias.setBackground(new java.awt.Color(0, 0, 0));
        calorias.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        calorias.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(calorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 60, 20));

        jPanel4.setBackground(new java.awt.Color(0, 153, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Calorías      Proteinas       Hidratos      Grasas");
        jPanel4.add(jLabel3);

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 450, 80));

        jLabel1.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("TUS DATOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 100, 40));

        jLabel5.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("TUS MACROS DIARIOS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 190, 40));

        btnModificar.setBackground(new java.awt.Color(51, 153, 255));
        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar Datos");
        btnModificar.setBorder(new javax.swing.border.MatteBorder(null));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 160, 50));

        nota.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nota.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(nota, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 740, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 820, 550));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        MenuPrincipal mp = new MenuPrincipal(usuario);
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        ModificarDatos md = new ModificarDatos(usuario);
        md.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    @Override
    public Image getIconImage() {
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logo.png"));

        return icono;
    }

    public static void main(String args[]) {

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfil().setVisible(true);
            }
        });
    }

    public void cargarDatos() {

        //PARTE DE LOS DATOS
        bienvenido.setText("Bienvenido " + usuario);
        try {
            Conexion.conectar();
            PreparedStatement ps = Conexion.conectar().prepareStatement("SELECT * FROM Usuarios WHERE nombre = ?");
            ps.setString(1, usuario);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {

                nombre.setText(rs.getString(2));
                pesoInicial.setText(String.valueOf(rs.getInt(6)) + " Kgs");
                pesoActual.setText(String.valueOf(rs.getInt(9)) + " Kgs");
                altura.setText(rs.getInt(5) + " cm");

                String objetivoBd = rs.getString(7);
                System.out.println("El OBJETIVO NUMERO ONEEEEEEE ESSSSS   " + objetivoBd);
                if (objetivoBd != null) {

                    if (objetivoBd.equals("0")) {
                        objetivo.setText("Perder");

                    } else if (objetivoBd.equals("1")) {
                        objetivo.setText("Ganar");

                    } else {

                        objetivo.setText("Mantener");

                    }

                }

            }

            Conexion.conectar().close();

        } catch (SQLException e) {

            System.err.println("Error en la base de datos " + e);

        }

        //PARTE MACROS    
        /*Para hombres, la fórmula original de Harris-Benedict es la siguiente:
                     RMB = 66 + (13.75 x peso en kg) + (5 x altura en cm) – (6.75 x edad en años)
                     Para mujeres, la fórmula es ligeramente diferente:
                     RMB = 655 + (9.56 x peso en kg) + (1.85 x altura en cm) - (4.68 x edad en años)*/
        try {
            Conexion.conectar();
            PreparedStatement ps1 = Conexion.conectar().prepareStatement("SELECT * FROM Usuarios WHERE nombre = ?");
            ps1.setString(1, usuario);
            ResultSet rs1 = ps1.executeQuery();

            while (rs1.next()) {
                String sNota;
                int sexo = rs1.getInt(8);
                int altura = rs1.getInt(5);
                int edad = rs1.getInt(10);
                float caloriasTotales;
                int pesoActual = rs1.getInt(9);
                int objetivoBd1 = rs1.getInt(7);
                System.out.println("el objetivo es " + rs1.getInt(7));

                if (sexo == 0) {
                    // Formula hombre

                    caloriasTotales = 66 + (13.75f * pesoActual) + (5 * altura) - (6.75f * edad);
                    System.out.println("El objetivo eeeeeeees: " + objetivoBd1);
                    if (objetivoBd1 == 0) {
                        System.out.println("Entra en el objetivo");
                        caloriasTotales -= 400;
                        calorias.setText(String.valueOf(caloriasTotales));
                        sNota = "Para mantenerte necesitas " + (caloriasTotales + 400) + " Kcal , pero dado tu objetivo debes hacer un deficit de entre 300 y 500 kcal menos.";
                        nota.setText(sNota);
                    } else if (objetivoBd1 == 1) {
                        caloriasTotales += 400;
                        calorias.setText(String.valueOf(caloriasTotales));
                        sNota = "Para mantenerte necesitas " + (caloriasTotales - 400) + " Kcal , pero dado tu objetivo debes hacer un superhabit de entre 300 y 500 kcal mas";
                        nota.setText(sNota);
                    } else {
                        calorias.setText(String.valueOf(caloriasTotales));
                    }

                    System.out.println("Calorías totales (hombre): " + caloriasTotales);
                } else if (sexo == 1) {
                    // Formula mujer
                    caloriasTotales = 655 + (9.56f * pesoActual) + (1.85f * altura) - (4.68f * edad);
                    calorias.setText(String.valueOf(caloriasTotales));
                    if (objetivoBd1 == 0) {
                        caloriasTotales -= 300;
                        calorias.setText(String.valueOf(caloriasTotales));
                        sNota = "Para mantenerte necesitas " + caloriasTotales + " Kcal , pero dado tu objetivo debes hacer un deficit de unas 300 kcal menos";
                        nota.setText(sNota);
                    } else if (objetivoBd1 == 1) {
                        caloriasTotales += 300;
                        calorias.setText(String.valueOf(caloriasTotales));
                        sNota = "Para mantenerte necesitas " + caloriasTotales + " Kcal , pero dado tu objetivo debes hacer un superhabit de unas 300 kcal mas";
                        nota.setText(sNota);
                    } else {
                        calorias.setText(String.valueOf(caloriasTotales));
                    }

                    System.out.println("Calorías totales (mujer): " + caloriasTotales);
                } else {
                    // Sexo no especificado, asignar un valor predeterminado
                    caloriasTotales = 0;
                }

                // Calcular macros para ganar masa muscular
                int proteinasTotales = (int) (pesoActual * 2.2f);  // 2.2 gramos de proteína por kilogramo de peso corporal
                int grasasTotales = (int) (caloriasTotales * 0.3f) / 9;  // 30% de calorías de grasas
                int carbohidratosTotales = (int) (caloriasTotales * 0.5f) / 4;
                proteinas.setText(String.valueOf(proteinasTotales) + " G");
                grasas.setText(String.valueOf(grasasTotales) + " G");
                hidratos.setText(String.valueOf(carbohidratosTotales) + " G");
                System.out.println("Sexo " + sexo + " Edad " + edad + " altura " + altura + " peso " + pesoActual + " calorias " + caloriasTotales);
            }

            Conexion.conectar().close();

        } catch (SQLException e) {

            System.err.println("Error en la base de datos " + e);

        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel altura;
    private javax.swing.JLabel bienvenido;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel calorias;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel grasas;
    private javax.swing.JLabel hidratos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel nota;
    private javax.swing.JLabel objetivo;
    private javax.swing.JLabel objetivo1;
    private javax.swing.JLabel pesoActual;
    private javax.swing.JLabel pesoInicial;
    private javax.swing.JLabel proteinas;
    private javax.swing.JLabel texto;
    // End of variables declaration//GEN-END:variables
}
