/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tjavacomun;

import bbdd.Conexion;
import com.sun.jdi.connect.spi.Connection;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import bbdd.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
//
/**
 *
 * @author Usuario
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Registro() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("MACROSLEAF");
        setIconImage(getIconImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        texto = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnEntrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rBtnMant = new javax.swing.JRadioButton();
        rBtnPerder = new javax.swing.JRadioButton();
        rBtnGanar = new javax.swing.JRadioButton();
        txtUsu = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        spinPeso = new javax.swing.JSpinner();
        spinAltura = new javax.swing.JSpinner();
        txtPass = new javax.swing.JPasswordField();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texto.setFont(new java.awt.Font("Times New Roman", 1, 56)); // NOI18N
        texto.setForeground(new java.awt.Color(255, 255, 255));
        texto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/texto.png"))); // NOI18N
        getContentPane().add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 620, 150));

        btnSalir.setBackground(new java.awt.Color(0, 0, 255));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Atrás");
        btnSalir.setBorder(new javax.swing.border.MatteBorder(null));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 740, 160, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEntrar.setBackground(new java.awt.Color(0, 0, 255));
        btnEntrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("Regístrate");
        btnEntrar.setBorder(new javax.swing.border.MatteBorder(null));
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 160, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("E-mail :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 170, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre Usuario :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 170, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Contraseña :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 170, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Altura (cm) :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 130, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Peso (Kg) : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 170, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Objetivo :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 130, 30));

        rBtnMant.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rBtnMant);
        rBtnMant.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rBtnMant.setForeground(new java.awt.Color(0, 0, 0));
        rBtnMant.setText("Mantenerse");
        rBtnMant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnMantActionPerformed(evt);
            }
        });
        jPanel1.add(rBtnMant, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, -1, -1));

        rBtnPerder.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rBtnPerder);
        rBtnPerder.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rBtnPerder.setForeground(new java.awt.Color(0, 0, 0));
        rBtnPerder.setText("Perder Peso");
        rBtnPerder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnPerderActionPerformed(evt);
            }
        });
        jPanel1.add(rBtnPerder, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, -1, -1));

        rBtnGanar.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rBtnGanar);
        rBtnGanar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rBtnGanar.setForeground(new java.awt.Color(0, 0, 0));
        rBtnGanar.setText("Ganar Peso");
        rBtnGanar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnGanarActionPerformed(evt);
            }
        });
        jPanel1.add(rBtnGanar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, -1, -1));

        txtUsu.setBackground(new java.awt.Color(255, 255, 255));
        txtUsu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtUsu.setForeground(new java.awt.Color(0, 0, 0));
        txtUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 320, 50));

        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 280, 50));

        spinPeso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(spinPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 90, 40));

        spinAltura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(spinAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 90, 40));

        txtPass.setBackground(new java.awt.Color(255, 255, 255));
        txtPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPass.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 290, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 820, 550));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed

        int valuePeso = (int) spinPeso.getValue();
        int valueAltura = (int) spinAltura.getValue();

        
        ButtonModel selectedButtonModel = buttonGroup1.getSelection();
        int selectedObjective = -1; // Por defecto, ningún objetivo seleccionado

        if (selectedButtonModel != null) {
            if (selectedButtonModel.equals(rBtnPerder.getModel())) {
                selectedObjective = 0; // Por ejemplo, el objetivo 0
            } else if (selectedButtonModel.equals(rBtnGanar.getModel())) {
                selectedObjective = 1; // Por ejemplo, el objetivo 1
            } else if (selectedButtonModel.equals(rBtnMant.getModel())) {
                selectedObjective = 2; // Por ejemplo, el objetivo 2
            }
        }

        if (txtUsu.getText().length() < 6) {
            JOptionPane.showMessageDialog(null, "El nombre no puede contener menos de 3 caracteres...", "Alerta", JOptionPane.INFORMATION_MESSAGE);
        } else if (txtEmail.getText().length() < 12) {
            JOptionPane.showMessageDialog(null, "El apellido no puede contener menos de 3 caracteres...", "Alerta", JOptionPane.INFORMATION_MESSAGE);

        } else if (txtPass.getText().length() < 6) {
            JOptionPane.showMessageDialog(null, "El DNI debe contener 9 caracteres ...", "Alerta", JOptionPane.INFORMATION_MESSAGE);

        } else if (valuePeso == 0 || valueAltura == 0) {
            JOptionPane.showMessageDialog(null, "Debe Rellenar el Peso y la Altura correctamente", "Alerta", JOptionPane.INFORMATION_MESSAGE);

        } else if (buttonGroup1.getSelection() == null) {

            JOptionPane.showMessageDialog(null, "Debe Marcar un OBJETIVO", "Alerta", JOptionPane.INFORMATION_MESSAGE);
        } else {
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que los datos introducidos son correctos?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_OPTION) {
                try {
                    Conexion.conectar();
                    PreparedStatement verificar = Conexion.conectar().prepareStatement("SELECT * FROM Usuarios WHERE nombre = ?");
                    verificar.setString(1, txtUsu.getText());
                    ResultSet rs = verificar.executeQuery();
                    if (rs.next()) {
                        JOptionPane.showMessageDialog(null, "Ese Cliente ya existe en nuestra base de datos", "Usuario existente", JOptionPane.WARNING_MESSAGE);
                    } else {
                        PreparedStatement insertar = Conexion.conectar().prepareStatement("INSERT INTO Usuarios (nombre,email,contraseña,altura,peso,objetivo) VALUES (?,?,?,?,?,?)");
                        insertar.setString(1, txtUsu.getText());
                        insertar.setString(2, txtEmail.getText());
                        insertar.setString(3, txtPass.getText());
                        insertar.setString(4, spinAltura.getValue().toString());
                        insertar.setString(5, spinPeso.getValue().toString());
                        insertar.setInt(6, selectedObjective);
                        System.out.println(selectedObjective);
                        insertar.executeUpdate();
                        Conexion.conectar().close();
                        JOptionPane.showMessageDialog(null, "Usuario Registrado con Éxito");
                        this.dispose();
                        Main main = new Main();
                        main.setVisible(true);
                    }
                } catch (SQLException e) {
                    System.out.println("Error en la conexión: " + e);
                }
            } else if (respuesta == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "Introduce los nuevos datos y asegúrate de que sean correctos...", "Información", JOptionPane.INFORMATION_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        Main main = new Main();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void rBtnMantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnMantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBtnMantActionPerformed

    private void rBtnPerderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnPerderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBtnPerderActionPerformed

    private void rBtnGanarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnGanarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBtnGanarActionPerformed

    private void txtUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    @Override
    public Image getIconImage() {
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logo.png"));

        return icono;
    }

    public static void main(String args[]) {

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rBtnGanar;
    private javax.swing.JRadioButton rBtnMant;
    private javax.swing.JRadioButton rBtnPerder;
    private javax.swing.JSpinner spinAltura;
    private javax.swing.JSpinner spinPeso;
    private javax.swing.JLabel texto;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsu;
    // End of variables declaration//GEN-END:variables
}
